# -*- mode: python ; coding: utf-8 -*-

datas = []
binaries = []

hiddenimports = [
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
    'PySide6.QtSvg',
    'openpyxl',
    'sqlite3',
    'orby',
    'orby.core',
    'orby.core.models',
    'orby.database',
    'orby.repository',
    'orby.importer',
    'orby.ui',
    'orby.ui.tokens',
    'orby.ui.icons',
    'orby.ui.theme',
    'orby.ui.components',
    'orby.ui.login_dialog',
    'orby.main_window',
]

excludes = [
    'PySide6.QtWebEngineCore',
    'PySide6.QtWebEngineWidgets',
    'PySide6.QtWebEngineQuick',
    'PySide6.Qt3DCore',
    'PySide6.Qt3DRender',
    'PySide6.Qt3DInput',
    'PySide6.Qt3DLogic',
    'PySide6.Qt3DAnimation',
    'PySide6.Qt3DExtras',
    'PySide6.QtQuick',
    'PySide6.QtQuickWidgets',
    'PySide6.QtQuick3D',
    'PySide6.QtQml',
    'PySide6.QtMultimedia',
    'PySide6.QtMultimediaWidgets',
    'PySide6.QtDesigner',
    'PySide6.QtHelp',
    'PySide6.QtSql',
    'PySide6.QtTest',
    'PySide6.QtSensors',
    'PySide6.QtSerialPort',
    'PySide6.QtBluetooth',
    'PySide6.QtNfc',
    'PySide6.QtPositioning',
    'PySide6.QtScxml',
    'PySide6.QtRemoteObjects',
    'PySide6.QtVirtualKeyboard',
    'PySide6.QtCharts',
    'PySide6.QtDataVisualization',
    'PySide6.QtPdf',
    'PySide6.QtPdfWidgets',
    'tkinter',
    'unittest',
]

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Orby',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
